development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
#  database: shopelia-dev
#  adapter: postgresql
#  host: curie.epicdream.fr
#  port: 5432
#  pool: 3
#  timeout: 5000
#  username: s_db_user
#  password: bH8p_LDt

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
#  database: shopelia-test
#  adapter: postgresql
#  host: curie.epicdream.fr
#  port: 5432
#  pool: 3
#  timeout: 5000
#  username: s_db_user
#  password: bH8p_LDt

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
  
